require 'ffi'
require 'singleton'

class Model

  # WARNING: this is not thread safe
  def initialize
    reset
  end

  def reset
    C.reset
  end

  def method_missing(name, *arguments)
    if arguments.size == 0
      get(name)
    elsif arguments.size == 1
      set(name, arguments.first)
    else
      super
    end 
  end

  def get(name)
    return 0 unless C.respond_to?(name)
    ruby_value_from_excel_value(C.send(name))
  end

  def ruby_value_from_excel_value(excel_value)
    case excel_value[:type]
    when :ExcelNumber; excel_value[:number]
    when :ExcelString; excel_value[:string].read_string.force_encoding("utf-8")
    when :ExcelBoolean; excel_value[:number] == 1
    when :ExcelEmpty; nil
    when :ExcelRange
      r = excel_value[:rows]
      c = excel_value[:columns]
      p = excel_value[:array]
      s = C::ExcelValue.size
      a = Array.new(r) { Array.new(c) }
      (0...r).each do |row|
        (0...c).each do |column|
          a[row][column] = ruby_value_from_excel_value(C::ExcelValue.new(p + (((row*c)+column)*s)))
        end
      end 
      return a
    when :ExcelError; [:value,:name,:div0,:ref,:na,:num][excel_value[:number]]
    else
      raise Exception.new("ExcelValue type #{excel_value[:type].inspect} not recognised")
    end
  end

  def set(name, ruby_value)
    name = name.to_s
    name = "set_#{name[0..-2]}" if name.end_with?('=')
    return false unless C.respond_to?(name)
    C.send(name, excel_value_from_ruby_value(ruby_value))
  end

  def excel_value_from_ruby_value(ruby_value, excel_value = C::ExcelValue.new)
    case ruby_value
    when Numeric
      excel_value[:type] = :ExcelNumber
      excel_value[:number] = ruby_value
    when String
      excel_value[:type] = :ExcelString
      excel_value[:string] = FFI::MemoryPointer.from_string(ruby_value.encode('utf-8'))
    when TrueClass, FalseClass
      excel_value[:type] = :ExcelBoolean
      excel_value[:number] = ruby_value ? 1 : 0
    when nil
      excel_value[:type] = :ExcelEmpty
    when Array
      excel_value[:type] = :ExcelRange
      # Presumed to be a row unless specified otherwise
      if ruby_value.first.is_a?(Array)
        excel_value[:rows] = ruby_value.size
        excel_value[:columns] = ruby_value.first.size
      else
        excel_value[:rows] = 1
        excel_value[:columns] = ruby_value.size
      end
      ruby_values = ruby_value.flatten
      pointer = FFI::MemoryPointer.new(C::ExcelValue, ruby_values.size)
      excel_value[:array] = pointer
      ruby_values.each.with_index do |v,i|
        excel_value_from_ruby_value(v, C::ExcelValue.new(pointer[i]))
      end
    when Symbol
      excel_value[:type] = :ExcelError
      excel_value[:number] = [:value, :name, :div0, :ref, :na].index(ruby_value)
    else
      raise Exception.new("Ruby value #{ruby_value.inspect} not translatable into excel")
    end
    excel_value
  end


  module C 
    extend FFI::Library
    ffi_lib  File.join(File.dirname(__FILE__),FFI.map_library_name('model'))
    ExcelType = enum :ExcelEmpty, :ExcelNumber, :ExcelString, :ExcelBoolean, :ExcelError, :ExcelRange
                  
    class ExcelValue < FFI::Struct
      layout :type, ExcelType,
             :number, :double,
             :string, :pointer,
             :array, :pointer,
             :rows, :int,
             :columns, :int             
    end
  

    # use this function to reset all cell values
    attach_function 'reset', [], :void
    attach_function 'results_e583', [], ExcelValue.by_value
    attach_function 'results_f583', [], ExcelValue.by_value
    attach_function 'results_g583', [], ExcelValue.by_value
    attach_function 'results_h583', [], ExcelValue.by_value
    attach_function 'results_i583', [], ExcelValue.by_value
    attach_function 'results_j583', [], ExcelValue.by_value
    attach_function 'results_k583', [], ExcelValue.by_value
    attach_function 'results_l583', [], ExcelValue.by_value
    attach_function 'results_m583', [], ExcelValue.by_value
    attach_function 'results_n583', [], ExcelValue.by_value
    attach_function 'results_o583', [], ExcelValue.by_value
    attach_function 'results_p583', [], ExcelValue.by_value
    attach_function 'results_q583', [], ExcelValue.by_value
    attach_function 'results_r583', [], ExcelValue.by_value
    attach_function 'results_s583', [], ExcelValue.by_value
    attach_function 'results_t583', [], ExcelValue.by_value
    attach_function 'results_u583', [], ExcelValue.by_value
    attach_function 'results_v583', [], ExcelValue.by_value
    attach_function 'results_w583', [], ExcelValue.by_value
    attach_function 'results_e584', [], ExcelValue.by_value
    attach_function 'results_f584', [], ExcelValue.by_value
    attach_function 'results_g584', [], ExcelValue.by_value
    attach_function 'results_h584', [], ExcelValue.by_value
    attach_function 'results_i584', [], ExcelValue.by_value
    attach_function 'results_j584', [], ExcelValue.by_value
    attach_function 'results_k584', [], ExcelValue.by_value
    attach_function 'results_l584', [], ExcelValue.by_value
    attach_function 'results_m584', [], ExcelValue.by_value
    attach_function 'results_n584', [], ExcelValue.by_value
    attach_function 'results_o584', [], ExcelValue.by_value
    attach_function 'results_p584', [], ExcelValue.by_value
    attach_function 'results_q584', [], ExcelValue.by_value
    attach_function 'results_r584', [], ExcelValue.by_value
    attach_function 'results_s584', [], ExcelValue.by_value
    attach_function 'results_t584', [], ExcelValue.by_value
    attach_function 'results_u584', [], ExcelValue.by_value
    attach_function 'results_v584', [], ExcelValue.by_value
    attach_function 'results_w584', [], ExcelValue.by_value
    attach_function 'results_e585', [], ExcelValue.by_value
    attach_function 'results_f585', [], ExcelValue.by_value
    attach_function 'results_g585', [], ExcelValue.by_value
    attach_function 'results_h585', [], ExcelValue.by_value
    attach_function 'results_i585', [], ExcelValue.by_value
    attach_function 'results_j585', [], ExcelValue.by_value
    attach_function 'results_k585', [], ExcelValue.by_value
    attach_function 'results_l585', [], ExcelValue.by_value
    attach_function 'results_m585', [], ExcelValue.by_value
    attach_function 'results_n585', [], ExcelValue.by_value
    attach_function 'results_o585', [], ExcelValue.by_value
    attach_function 'results_p585', [], ExcelValue.by_value
    attach_function 'results_q585', [], ExcelValue.by_value
    attach_function 'results_r585', [], ExcelValue.by_value
    attach_function 'results_s585', [], ExcelValue.by_value
    attach_function 'results_t585', [], ExcelValue.by_value
    attach_function 'results_u585', [], ExcelValue.by_value
    attach_function 'results_v585', [], ExcelValue.by_value
    attach_function 'results_w585', [], ExcelValue.by_value
    attach_function 'results_e586', [], ExcelValue.by_value
    attach_function 'results_f586', [], ExcelValue.by_value
    attach_function 'results_g586', [], ExcelValue.by_value
    attach_function 'results_h586', [], ExcelValue.by_value
    attach_function 'results_i586', [], ExcelValue.by_value
    attach_function 'results_j586', [], ExcelValue.by_value
    attach_function 'results_k586', [], ExcelValue.by_value
    attach_function 'results_l586', [], ExcelValue.by_value
    attach_function 'results_m586', [], ExcelValue.by_value
    attach_function 'results_n586', [], ExcelValue.by_value
    attach_function 'results_o586', [], ExcelValue.by_value
    attach_function 'results_p586', [], ExcelValue.by_value
    attach_function 'results_q586', [], ExcelValue.by_value
    attach_function 'results_r586', [], ExcelValue.by_value
    attach_function 'results_s586', [], ExcelValue.by_value
    attach_function 'results_t586', [], ExcelValue.by_value
    attach_function 'results_u586', [], ExcelValue.by_value
    attach_function 'results_v586', [], ExcelValue.by_value
    attach_function 'results_w586', [], ExcelValue.by_value
    attach_function 'results_e587', [], ExcelValue.by_value
    attach_function 'results_f587', [], ExcelValue.by_value
    attach_function 'results_g587', [], ExcelValue.by_value
    attach_function 'results_h587', [], ExcelValue.by_value
    attach_function 'results_i587', [], ExcelValue.by_value
    attach_function 'results_j587', [], ExcelValue.by_value
    attach_function 'results_k587', [], ExcelValue.by_value
    attach_function 'results_l587', [], ExcelValue.by_value
    attach_function 'results_m587', [], ExcelValue.by_value
    attach_function 'results_n587', [], ExcelValue.by_value
    attach_function 'results_o587', [], ExcelValue.by_value
    attach_function 'results_p587', [], ExcelValue.by_value
    attach_function 'results_q587', [], ExcelValue.by_value
    attach_function 'results_r587', [], ExcelValue.by_value
    attach_function 'results_s587', [], ExcelValue.by_value
    attach_function 'results_t587', [], ExcelValue.by_value
    attach_function 'results_u587', [], ExcelValue.by_value
    attach_function 'results_v587', [], ExcelValue.by_value
    attach_function 'results_w587', [], ExcelValue.by_value
    attach_function 'results_e588', [], ExcelValue.by_value
    attach_function 'results_f588', [], ExcelValue.by_value
    attach_function 'results_g588', [], ExcelValue.by_value
    attach_function 'results_h588', [], ExcelValue.by_value
    attach_function 'results_i588', [], ExcelValue.by_value
    attach_function 'results_j588', [], ExcelValue.by_value
    attach_function 'results_k588', [], ExcelValue.by_value
    attach_function 'results_l588', [], ExcelValue.by_value
    attach_function 'results_m588', [], ExcelValue.by_value
    attach_function 'results_n588', [], ExcelValue.by_value
    attach_function 'results_o588', [], ExcelValue.by_value
    attach_function 'results_p588', [], ExcelValue.by_value
    attach_function 'results_q588', [], ExcelValue.by_value
    attach_function 'results_r588', [], ExcelValue.by_value
    attach_function 'results_s588', [], ExcelValue.by_value
    attach_function 'results_t588', [], ExcelValue.by_value
    attach_function 'results_u588', [], ExcelValue.by_value
    attach_function 'results_v588', [], ExcelValue.by_value
    attach_function 'results_w588', [], ExcelValue.by_value
    attach_function 'results_e589', [], ExcelValue.by_value
    attach_function 'results_f589', [], ExcelValue.by_value
    attach_function 'results_g589', [], ExcelValue.by_value
    attach_function 'results_h589', [], ExcelValue.by_value
    attach_function 'results_i589', [], ExcelValue.by_value
    attach_function 'results_j589', [], ExcelValue.by_value
    attach_function 'results_k589', [], ExcelValue.by_value
    attach_function 'results_l589', [], ExcelValue.by_value
    attach_function 'results_m589', [], ExcelValue.by_value
    attach_function 'results_n589', [], ExcelValue.by_value
    attach_function 'results_o589', [], ExcelValue.by_value
    attach_function 'results_p589', [], ExcelValue.by_value
    attach_function 'results_q589', [], ExcelValue.by_value
    attach_function 'results_r589', [], ExcelValue.by_value
    attach_function 'results_s589', [], ExcelValue.by_value
    attach_function 'results_t589', [], ExcelValue.by_value
    attach_function 'results_u589', [], ExcelValue.by_value
    attach_function 'results_v589', [], ExcelValue.by_value
    attach_function 'results_w589', [], ExcelValue.by_value
    attach_function 'results_e590', [], ExcelValue.by_value
    attach_function 'results_f590', [], ExcelValue.by_value
    attach_function 'results_g590', [], ExcelValue.by_value
    attach_function 'results_h590', [], ExcelValue.by_value
    attach_function 'results_i590', [], ExcelValue.by_value
    attach_function 'results_j590', [], ExcelValue.by_value
    attach_function 'results_k590', [], ExcelValue.by_value
    attach_function 'results_l590', [], ExcelValue.by_value
    attach_function 'results_m590', [], ExcelValue.by_value
    attach_function 'results_n590', [], ExcelValue.by_value
    attach_function 'results_o590', [], ExcelValue.by_value
    attach_function 'results_p590', [], ExcelValue.by_value
    attach_function 'results_q590', [], ExcelValue.by_value
    attach_function 'results_r590', [], ExcelValue.by_value
    attach_function 'results_s590', [], ExcelValue.by_value
    attach_function 'results_t590', [], ExcelValue.by_value
    attach_function 'results_u590', [], ExcelValue.by_value
    attach_function 'results_v590', [], ExcelValue.by_value
    attach_function 'results_w590', [], ExcelValue.by_value
    attach_function 'results_e591', [], ExcelValue.by_value
    attach_function 'results_f591', [], ExcelValue.by_value
    attach_function 'results_g591', [], ExcelValue.by_value
    attach_function 'results_h591', [], ExcelValue.by_value
    attach_function 'results_i591', [], ExcelValue.by_value
    attach_function 'results_j591', [], ExcelValue.by_value
    attach_function 'results_k591', [], ExcelValue.by_value
    attach_function 'results_l591', [], ExcelValue.by_value
    attach_function 'results_m591', [], ExcelValue.by_value
    attach_function 'results_n591', [], ExcelValue.by_value
    attach_function 'results_o591', [], ExcelValue.by_value
    attach_function 'results_p591', [], ExcelValue.by_value
    attach_function 'results_q591', [], ExcelValue.by_value
    attach_function 'results_r591', [], ExcelValue.by_value
    attach_function 'results_s591', [], ExcelValue.by_value
    attach_function 'results_t591', [], ExcelValue.by_value
    attach_function 'results_u591', [], ExcelValue.by_value
    attach_function 'results_v591', [], ExcelValue.by_value
    attach_function 'results_w591', [], ExcelValue.by_value
    attach_function 'results_e526', [], ExcelValue.by_value
    attach_function 'results_f526', [], ExcelValue.by_value
    attach_function 'results_g526', [], ExcelValue.by_value
    attach_function 'results_h526', [], ExcelValue.by_value
    attach_function 'results_i526', [], ExcelValue.by_value
    attach_function 'results_j526', [], ExcelValue.by_value
    attach_function 'results_k526', [], ExcelValue.by_value
    attach_function 'results_l526', [], ExcelValue.by_value
    attach_function 'results_m526', [], ExcelValue.by_value
    attach_function 'results_n526', [], ExcelValue.by_value
    attach_function 'results_o526', [], ExcelValue.by_value
    attach_function 'results_p526', [], ExcelValue.by_value
    attach_function 'results_q526', [], ExcelValue.by_value
    attach_function 'results_r526', [], ExcelValue.by_value
    attach_function 'results_s526', [], ExcelValue.by_value
    attach_function 'results_t526', [], ExcelValue.by_value
    attach_function 'results_u526', [], ExcelValue.by_value
    attach_function 'results_v526', [], ExcelValue.by_value
    attach_function 'results_w526', [], ExcelValue.by_value
    attach_function 'results_e527', [], ExcelValue.by_value
    attach_function 'results_f527', [], ExcelValue.by_value
    attach_function 'results_g527', [], ExcelValue.by_value
    attach_function 'results_h527', [], ExcelValue.by_value
    attach_function 'results_i527', [], ExcelValue.by_value
    attach_function 'results_j527', [], ExcelValue.by_value
    attach_function 'results_k527', [], ExcelValue.by_value
    attach_function 'results_l527', [], ExcelValue.by_value
    attach_function 'results_m527', [], ExcelValue.by_value
    attach_function 'results_n527', [], ExcelValue.by_value
    attach_function 'results_o527', [], ExcelValue.by_value
    attach_function 'results_p527', [], ExcelValue.by_value
    attach_function 'results_q527', [], ExcelValue.by_value
    attach_function 'results_r527', [], ExcelValue.by_value
    attach_function 'results_s527', [], ExcelValue.by_value
    attach_function 'results_t527', [], ExcelValue.by_value
    attach_function 'results_u527', [], ExcelValue.by_value
    attach_function 'results_v527', [], ExcelValue.by_value
    attach_function 'results_w527', [], ExcelValue.by_value
    attach_function 'results_e528', [], ExcelValue.by_value
    attach_function 'results_f528', [], ExcelValue.by_value
    attach_function 'results_g528', [], ExcelValue.by_value
    attach_function 'results_h528', [], ExcelValue.by_value
    attach_function 'results_i528', [], ExcelValue.by_value
    attach_function 'results_j528', [], ExcelValue.by_value
    attach_function 'results_k528', [], ExcelValue.by_value
    attach_function 'results_l528', [], ExcelValue.by_value
    attach_function 'results_m528', [], ExcelValue.by_value
    attach_function 'results_n528', [], ExcelValue.by_value
    attach_function 'results_o528', [], ExcelValue.by_value
    attach_function 'results_p528', [], ExcelValue.by_value
    attach_function 'results_q528', [], ExcelValue.by_value
    attach_function 'results_r528', [], ExcelValue.by_value
    attach_function 'results_s528', [], ExcelValue.by_value
    attach_function 'results_t528', [], ExcelValue.by_value
    attach_function 'results_u528', [], ExcelValue.by_value
    attach_function 'results_v528', [], ExcelValue.by_value
    attach_function 'results_w528', [], ExcelValue.by_value
    attach_function 'results_e529', [], ExcelValue.by_value
    attach_function 'results_f529', [], ExcelValue.by_value
    attach_function 'results_g529', [], ExcelValue.by_value
    attach_function 'results_h529', [], ExcelValue.by_value
    attach_function 'results_i529', [], ExcelValue.by_value
    attach_function 'results_j529', [], ExcelValue.by_value
    attach_function 'results_k529', [], ExcelValue.by_value
    attach_function 'results_l529', [], ExcelValue.by_value
    attach_function 'results_m529', [], ExcelValue.by_value
    attach_function 'results_n529', [], ExcelValue.by_value
    attach_function 'results_o529', [], ExcelValue.by_value
    attach_function 'results_p529', [], ExcelValue.by_value
    attach_function 'results_q529', [], ExcelValue.by_value
    attach_function 'results_r529', [], ExcelValue.by_value
    attach_function 'results_s529', [], ExcelValue.by_value
    attach_function 'results_t529', [], ExcelValue.by_value
    attach_function 'results_u529', [], ExcelValue.by_value
    attach_function 'results_v529', [], ExcelValue.by_value
    attach_function 'results_w529', [], ExcelValue.by_value
    attach_function 'results_e530', [], ExcelValue.by_value
    attach_function 'results_f530', [], ExcelValue.by_value
    attach_function 'results_g530', [], ExcelValue.by_value
    attach_function 'results_h530', [], ExcelValue.by_value
    attach_function 'results_i530', [], ExcelValue.by_value
    attach_function 'results_j530', [], ExcelValue.by_value
    attach_function 'results_k530', [], ExcelValue.by_value
    attach_function 'results_l530', [], ExcelValue.by_value
    attach_function 'results_m530', [], ExcelValue.by_value
    attach_function 'results_n530', [], ExcelValue.by_value
    attach_function 'results_o530', [], ExcelValue.by_value
    attach_function 'results_p530', [], ExcelValue.by_value
    attach_function 'results_q530', [], ExcelValue.by_value
    attach_function 'results_r530', [], ExcelValue.by_value
    attach_function 'results_s530', [], ExcelValue.by_value
    attach_function 'results_t530', [], ExcelValue.by_value
    attach_function 'results_u530', [], ExcelValue.by_value
    attach_function 'results_v530', [], ExcelValue.by_value
    attach_function 'results_w530', [], ExcelValue.by_value
    attach_function 'results_e531', [], ExcelValue.by_value
    attach_function 'results_f531', [], ExcelValue.by_value
    attach_function 'results_g531', [], ExcelValue.by_value
    attach_function 'results_h531', [], ExcelValue.by_value
    attach_function 'results_i531', [], ExcelValue.by_value
    attach_function 'results_j531', [], ExcelValue.by_value
    attach_function 'results_k531', [], ExcelValue.by_value
    attach_function 'results_l531', [], ExcelValue.by_value
    attach_function 'results_m531', [], ExcelValue.by_value
    attach_function 'results_n531', [], ExcelValue.by_value
    attach_function 'results_o531', [], ExcelValue.by_value
    attach_function 'results_p531', [], ExcelValue.by_value
    attach_function 'results_q531', [], ExcelValue.by_value
    attach_function 'results_r531', [], ExcelValue.by_value
    attach_function 'results_s531', [], ExcelValue.by_value
    attach_function 'results_t531', [], ExcelValue.by_value
    attach_function 'results_u531', [], ExcelValue.by_value
    attach_function 'results_v531', [], ExcelValue.by_value
    attach_function 'results_w531', [], ExcelValue.by_value
    attach_function 'results_e532', [], ExcelValue.by_value
    attach_function 'results_f532', [], ExcelValue.by_value
    attach_function 'results_g532', [], ExcelValue.by_value
    attach_function 'results_h532', [], ExcelValue.by_value
    attach_function 'results_i532', [], ExcelValue.by_value
    attach_function 'results_j532', [], ExcelValue.by_value
    attach_function 'results_k532', [], ExcelValue.by_value
    attach_function 'results_l532', [], ExcelValue.by_value
    attach_function 'results_m532', [], ExcelValue.by_value
    attach_function 'results_n532', [], ExcelValue.by_value
    attach_function 'results_o532', [], ExcelValue.by_value
    attach_function 'results_p532', [], ExcelValue.by_value
    attach_function 'results_q532', [], ExcelValue.by_value
    attach_function 'results_r532', [], ExcelValue.by_value
    attach_function 'results_s532', [], ExcelValue.by_value
    attach_function 'results_t532', [], ExcelValue.by_value
    attach_function 'results_u532', [], ExcelValue.by_value
    attach_function 'results_v532', [], ExcelValue.by_value
    attach_function 'results_w532', [], ExcelValue.by_value
    attach_function 'results_e533', [], ExcelValue.by_value
    attach_function 'results_f533', [], ExcelValue.by_value
    attach_function 'results_g533', [], ExcelValue.by_value
    attach_function 'results_h533', [], ExcelValue.by_value
    attach_function 'results_i533', [], ExcelValue.by_value
    attach_function 'results_j533', [], ExcelValue.by_value
    attach_function 'results_k533', [], ExcelValue.by_value
    attach_function 'results_l533', [], ExcelValue.by_value
    attach_function 'results_m533', [], ExcelValue.by_value
    attach_function 'results_n533', [], ExcelValue.by_value
    attach_function 'results_o533', [], ExcelValue.by_value
    attach_function 'results_p533', [], ExcelValue.by_value
    attach_function 'results_q533', [], ExcelValue.by_value
    attach_function 'results_r533', [], ExcelValue.by_value
    attach_function 'results_s533', [], ExcelValue.by_value
    attach_function 'results_t533', [], ExcelValue.by_value
    attach_function 'results_u533', [], ExcelValue.by_value
    attach_function 'results_v533', [], ExcelValue.by_value
    attach_function 'results_w533', [], ExcelValue.by_value
    attach_function 'results_e534', [], ExcelValue.by_value
    attach_function 'results_f534', [], ExcelValue.by_value
    attach_function 'results_g534', [], ExcelValue.by_value
    attach_function 'results_h534', [], ExcelValue.by_value
    attach_function 'results_i534', [], ExcelValue.by_value
    attach_function 'results_j534', [], ExcelValue.by_value
    attach_function 'results_k534', [], ExcelValue.by_value
    attach_function 'results_l534', [], ExcelValue.by_value
    attach_function 'results_m534', [], ExcelValue.by_value
    attach_function 'results_n534', [], ExcelValue.by_value
    attach_function 'results_o534', [], ExcelValue.by_value
    attach_function 'results_p534', [], ExcelValue.by_value
    attach_function 'results_q534', [], ExcelValue.by_value
    attach_function 'results_r534', [], ExcelValue.by_value
    attach_function 'results_s534', [], ExcelValue.by_value
    attach_function 'results_t534', [], ExcelValue.by_value
    attach_function 'results_u534', [], ExcelValue.by_value
    attach_function 'results_v534', [], ExcelValue.by_value
    attach_function 'results_w534', [], ExcelValue.by_value
    attach_function 'results_e535', [], ExcelValue.by_value
    attach_function 'results_f535', [], ExcelValue.by_value
    attach_function 'results_g535', [], ExcelValue.by_value
    attach_function 'results_h535', [], ExcelValue.by_value
    attach_function 'results_i535', [], ExcelValue.by_value
    attach_function 'results_j535', [], ExcelValue.by_value
    attach_function 'results_k535', [], ExcelValue.by_value
    attach_function 'results_l535', [], ExcelValue.by_value
    attach_function 'results_m535', [], ExcelValue.by_value
    attach_function 'results_n535', [], ExcelValue.by_value
    attach_function 'results_o535', [], ExcelValue.by_value
    attach_function 'results_p535', [], ExcelValue.by_value
    attach_function 'results_q535', [], ExcelValue.by_value
    attach_function 'results_r535', [], ExcelValue.by_value
    attach_function 'results_s535', [], ExcelValue.by_value
    attach_function 'results_t535', [], ExcelValue.by_value
    attach_function 'results_u535', [], ExcelValue.by_value
    attach_function 'results_v535', [], ExcelValue.by_value
    attach_function 'results_w535', [], ExcelValue.by_value
    attach_function 'results_e644', [], ExcelValue.by_value
    attach_function 'results_f644', [], ExcelValue.by_value
    attach_function 'results_g644', [], ExcelValue.by_value
    attach_function 'results_h644', [], ExcelValue.by_value
    attach_function 'results_i644', [], ExcelValue.by_value
    attach_function 'results_j644', [], ExcelValue.by_value
    attach_function 'results_k644', [], ExcelValue.by_value
    attach_function 'results_l644', [], ExcelValue.by_value
    attach_function 'results_m644', [], ExcelValue.by_value
    attach_function 'results_n644', [], ExcelValue.by_value
    attach_function 'results_o644', [], ExcelValue.by_value
    attach_function 'results_p644', [], ExcelValue.by_value
    attach_function 'results_q644', [], ExcelValue.by_value
    attach_function 'results_r644', [], ExcelValue.by_value
    attach_function 'results_s644', [], ExcelValue.by_value
    attach_function 'results_t644', [], ExcelValue.by_value
    attach_function 'results_u644', [], ExcelValue.by_value
    attach_function 'results_v644', [], ExcelValue.by_value
    attach_function 'results_w644', [], ExcelValue.by_value
    attach_function 'results_e645', [], ExcelValue.by_value
    attach_function 'results_f645', [], ExcelValue.by_value
    attach_function 'results_g645', [], ExcelValue.by_value
    attach_function 'results_h645', [], ExcelValue.by_value
    attach_function 'results_i645', [], ExcelValue.by_value
    attach_function 'results_j645', [], ExcelValue.by_value
    attach_function 'results_k645', [], ExcelValue.by_value
    attach_function 'results_l645', [], ExcelValue.by_value
    attach_function 'results_m645', [], ExcelValue.by_value
    attach_function 'results_n645', [], ExcelValue.by_value
    attach_function 'results_o645', [], ExcelValue.by_value
    attach_function 'results_p645', [], ExcelValue.by_value
    attach_function 'results_q645', [], ExcelValue.by_value
    attach_function 'results_r645', [], ExcelValue.by_value
    attach_function 'results_s645', [], ExcelValue.by_value
    attach_function 'results_t645', [], ExcelValue.by_value
    attach_function 'results_u645', [], ExcelValue.by_value
    attach_function 'results_v645', [], ExcelValue.by_value
    attach_function 'results_w645', [], ExcelValue.by_value
    attach_function 'results_e646', [], ExcelValue.by_value
    attach_function 'results_f646', [], ExcelValue.by_value
    attach_function 'results_g646', [], ExcelValue.by_value
    attach_function 'results_h646', [], ExcelValue.by_value
    attach_function 'results_i646', [], ExcelValue.by_value
    attach_function 'results_j646', [], ExcelValue.by_value
    attach_function 'results_k646', [], ExcelValue.by_value
    attach_function 'results_l646', [], ExcelValue.by_value
    attach_function 'results_m646', [], ExcelValue.by_value
    attach_function 'results_n646', [], ExcelValue.by_value
    attach_function 'results_o646', [], ExcelValue.by_value
    attach_function 'results_p646', [], ExcelValue.by_value
    attach_function 'results_q646', [], ExcelValue.by_value
    attach_function 'results_r646', [], ExcelValue.by_value
    attach_function 'results_s646', [], ExcelValue.by_value
    attach_function 'results_t646', [], ExcelValue.by_value
    attach_function 'results_u646', [], ExcelValue.by_value
    attach_function 'results_v646', [], ExcelValue.by_value
    attach_function 'results_w646', [], ExcelValue.by_value
    attach_function 'results_e647', [], ExcelValue.by_value
    attach_function 'results_f647', [], ExcelValue.by_value
    attach_function 'results_g647', [], ExcelValue.by_value
    attach_function 'results_h647', [], ExcelValue.by_value
    attach_function 'results_i647', [], ExcelValue.by_value
    attach_function 'results_j647', [], ExcelValue.by_value
    attach_function 'results_k647', [], ExcelValue.by_value
    attach_function 'results_l647', [], ExcelValue.by_value
    attach_function 'results_m647', [], ExcelValue.by_value
    attach_function 'results_n647', [], ExcelValue.by_value
    attach_function 'results_o647', [], ExcelValue.by_value
    attach_function 'results_p647', [], ExcelValue.by_value
    attach_function 'results_q647', [], ExcelValue.by_value
    attach_function 'results_r647', [], ExcelValue.by_value
    attach_function 'results_s647', [], ExcelValue.by_value
    attach_function 'results_t647', [], ExcelValue.by_value
    attach_function 'results_u647', [], ExcelValue.by_value
    attach_function 'results_v647', [], ExcelValue.by_value
    attach_function 'results_w647', [], ExcelValue.by_value
    attach_function 'results_e689', [], ExcelValue.by_value
    attach_function 'results_f689', [], ExcelValue.by_value
    attach_function 'results_g689', [], ExcelValue.by_value
    attach_function 'results_h689', [], ExcelValue.by_value
    attach_function 'results_i689', [], ExcelValue.by_value
    attach_function 'results_j689', [], ExcelValue.by_value
    attach_function 'results_k689', [], ExcelValue.by_value
    attach_function 'results_l689', [], ExcelValue.by_value
    attach_function 'results_m689', [], ExcelValue.by_value
    attach_function 'results_n689', [], ExcelValue.by_value
    attach_function 'results_o689', [], ExcelValue.by_value
    attach_function 'results_p689', [], ExcelValue.by_value
    attach_function 'results_q689', [], ExcelValue.by_value
    attach_function 'results_r689', [], ExcelValue.by_value
    attach_function 'results_s689', [], ExcelValue.by_value
    attach_function 'results_t689', [], ExcelValue.by_value
    attach_function 'results_u689', [], ExcelValue.by_value
    attach_function 'results_v689', [], ExcelValue.by_value
    attach_function 'results_w689', [], ExcelValue.by_value
    attach_function 'results_e690', [], ExcelValue.by_value
    attach_function 'results_f690', [], ExcelValue.by_value
    attach_function 'results_g690', [], ExcelValue.by_value
    attach_function 'results_h690', [], ExcelValue.by_value
    attach_function 'results_i690', [], ExcelValue.by_value
    attach_function 'results_j690', [], ExcelValue.by_value
    attach_function 'results_k690', [], ExcelValue.by_value
    attach_function 'results_l690', [], ExcelValue.by_value
    attach_function 'results_m690', [], ExcelValue.by_value
    attach_function 'results_n690', [], ExcelValue.by_value
    attach_function 'results_o690', [], ExcelValue.by_value
    attach_function 'results_p690', [], ExcelValue.by_value
    attach_function 'results_q690', [], ExcelValue.by_value
    attach_function 'results_r690', [], ExcelValue.by_value
    attach_function 'results_s690', [], ExcelValue.by_value
    attach_function 'results_t690', [], ExcelValue.by_value
    attach_function 'results_u690', [], ExcelValue.by_value
    attach_function 'results_v690', [], ExcelValue.by_value
    attach_function 'results_w690', [], ExcelValue.by_value
    attach_function 'results_e691', [], ExcelValue.by_value
    attach_function 'results_f691', [], ExcelValue.by_value
    attach_function 'results_g691', [], ExcelValue.by_value
    attach_function 'results_h691', [], ExcelValue.by_value
    attach_function 'results_i691', [], ExcelValue.by_value
    attach_function 'results_j691', [], ExcelValue.by_value
    attach_function 'results_k691', [], ExcelValue.by_value
    attach_function 'results_l691', [], ExcelValue.by_value
    attach_function 'results_m691', [], ExcelValue.by_value
    attach_function 'results_n691', [], ExcelValue.by_value
    attach_function 'results_o691', [], ExcelValue.by_value
    attach_function 'results_p691', [], ExcelValue.by_value
    attach_function 'results_q691', [], ExcelValue.by_value
    attach_function 'results_r691', [], ExcelValue.by_value
    attach_function 'results_s691', [], ExcelValue.by_value
    attach_function 'results_t691', [], ExcelValue.by_value
    attach_function 'results_u691', [], ExcelValue.by_value
    attach_function 'results_v691', [], ExcelValue.by_value
    attach_function 'results_w691', [], ExcelValue.by_value
    attach_function 'results_e692', [], ExcelValue.by_value
    attach_function 'results_f692', [], ExcelValue.by_value
    attach_function 'results_g692', [], ExcelValue.by_value
    attach_function 'results_h692', [], ExcelValue.by_value
    attach_function 'results_i692', [], ExcelValue.by_value
    attach_function 'results_j692', [], ExcelValue.by_value
    attach_function 'results_k692', [], ExcelValue.by_value
    attach_function 'results_l692', [], ExcelValue.by_value
    attach_function 'results_m692', [], ExcelValue.by_value
    attach_function 'results_n692', [], ExcelValue.by_value
    attach_function 'results_o692', [], ExcelValue.by_value
    attach_function 'results_p692', [], ExcelValue.by_value
    attach_function 'results_q692', [], ExcelValue.by_value
    attach_function 'results_r692', [], ExcelValue.by_value
    attach_function 'results_s692', [], ExcelValue.by_value
    attach_function 'results_t692', [], ExcelValue.by_value
    attach_function 'results_u692', [], ExcelValue.by_value
    attach_function 'results_v692', [], ExcelValue.by_value
    attach_function 'results_w692', [], ExcelValue.by_value
    # end of Results
    attach_function 'set_control_d17', [ExcelValue.by_value], :void
    attach_function 'set_control_d18', [ExcelValue.by_value], :void
    attach_function 'set_control_d19', [ExcelValue.by_value], :void
    attach_function 'set_control_d20', [ExcelValue.by_value], :void
    attach_function 'set_control_d21', [ExcelValue.by_value], :void
    attach_function 'set_control_d22', [ExcelValue.by_value], :void
    attach_function 'set_control_d23', [ExcelValue.by_value], :void
    attach_function 'set_control_d24', [ExcelValue.by_value], :void
    attach_function 'set_control_d25', [ExcelValue.by_value], :void
    attach_function 'set_control_d26', [ExcelValue.by_value], :void
    attach_function 'set_control_d27', [ExcelValue.by_value], :void
    attach_function 'set_control_d28', [ExcelValue.by_value], :void
    attach_function 'set_control_d29', [ExcelValue.by_value], :void
    attach_function 'set_control_d30', [ExcelValue.by_value], :void
    attach_function 'set_control_d31', [ExcelValue.by_value], :void
    attach_function 'set_control_d32', [ExcelValue.by_value], :void
    attach_function 'set_control_d33', [ExcelValue.by_value], :void
    attach_function 'set_control_d34', [ExcelValue.by_value], :void
    attach_function 'set_control_d35', [ExcelValue.by_value], :void
    attach_function 'set_control_d36', [ExcelValue.by_value], :void
    attach_function 'set_control_d37', [ExcelValue.by_value], :void
    attach_function 'set_control_d38', [ExcelValue.by_value], :void
    attach_function 'set_control_d39', [ExcelValue.by_value], :void
    attach_function 'set_control_d40', [ExcelValue.by_value], :void
    attach_function 'set_control_d41', [ExcelValue.by_value], :void
    attach_function 'set_control_d42', [ExcelValue.by_value], :void
    attach_function 'set_control_d43', [ExcelValue.by_value], :void
    attach_function 'set_control_d44', [ExcelValue.by_value], :void
    attach_function 'set_control_d45', [ExcelValue.by_value], :void
    attach_function 'set_control_d46', [ExcelValue.by_value], :void
    attach_function 'set_control_d47', [ExcelValue.by_value], :void
    attach_function 'set_control_d48', [ExcelValue.by_value], :void
    attach_function 'set_control_d49', [ExcelValue.by_value], :void
    attach_function 'set_control_d50', [ExcelValue.by_value], :void
    attach_function 'set_control_d51', [ExcelValue.by_value], :void
    attach_function 'set_control_d52', [ExcelValue.by_value], :void
    attach_function 'set_control_d53', [ExcelValue.by_value], :void
    attach_function 'set_control_d54', [ExcelValue.by_value], :void
    attach_function 'set_control_d55', [ExcelValue.by_value], :void
    attach_function 'set_control_d56', [ExcelValue.by_value], :void
    attach_function 'set_control_d57', [ExcelValue.by_value], :void
    attach_function 'set_control_d58', [ExcelValue.by_value], :void
    attach_function 'set_control_d59', [ExcelValue.by_value], :void
    attach_function 'set_control_d60', [ExcelValue.by_value], :void
    attach_function 'set_control_d61', [ExcelValue.by_value], :void
    attach_function 'set_control_d62', [ExcelValue.by_value], :void
    attach_function 'set_control_d63', [ExcelValue.by_value], :void
    attach_function 'set_control_d64', [ExcelValue.by_value], :void
    attach_function 'set_control_d65', [ExcelValue.by_value], :void
    attach_function 'set_control_d66', [ExcelValue.by_value], :void
    attach_function 'set_control_d67', [ExcelValue.by_value], :void
    attach_function 'set_control_g17', [ExcelValue.by_value], :void
    attach_function 'set_control_g18', [ExcelValue.by_value], :void
    attach_function 'set_control_g19', [ExcelValue.by_value], :void
    attach_function 'set_control_g20', [ExcelValue.by_value], :void
    attach_function 'set_control_g21', [ExcelValue.by_value], :void
    attach_function 'set_control_g22', [ExcelValue.by_value], :void
    attach_function 'set_control_g23', [ExcelValue.by_value], :void
    attach_function 'set_control_g24', [ExcelValue.by_value], :void
    attach_function 'set_control_g25', [ExcelValue.by_value], :void
    attach_function 'set_control_g26', [ExcelValue.by_value], :void
    attach_function 'set_control_g27', [ExcelValue.by_value], :void
    attach_function 'set_control_g28', [ExcelValue.by_value], :void
    attach_function 'set_control_g29', [ExcelValue.by_value], :void
    attach_function 'set_control_g30', [ExcelValue.by_value], :void
    attach_function 'set_control_g31', [ExcelValue.by_value], :void
    attach_function 'set_control_g32', [ExcelValue.by_value], :void
    attach_function 'set_control_g33', [ExcelValue.by_value], :void
    attach_function 'set_control_g34', [ExcelValue.by_value], :void
    attach_function 'set_control_g35', [ExcelValue.by_value], :void
    attach_function 'set_control_g36', [ExcelValue.by_value], :void
    attach_function 'set_control_g37', [ExcelValue.by_value], :void
    attach_function 'set_control_g38', [ExcelValue.by_value], :void
    attach_function 'set_control_g39', [ExcelValue.by_value], :void
    attach_function 'set_control_g40', [ExcelValue.by_value], :void
    attach_function 'set_control_g41', [ExcelValue.by_value], :void
    attach_function 'set_control_g42', [ExcelValue.by_value], :void
    attach_function 'set_control_g43', [ExcelValue.by_value], :void
    attach_function 'set_control_g44', [ExcelValue.by_value], :void
    attach_function 'set_control_g45', [ExcelValue.by_value], :void
    attach_function 'set_control_g46', [ExcelValue.by_value], :void
    attach_function 'set_control_g47', [ExcelValue.by_value], :void
    attach_function 'set_control_g48', [ExcelValue.by_value], :void
    attach_function 'set_control_g49', [ExcelValue.by_value], :void
    attach_function 'set_control_g50', [ExcelValue.by_value], :void
    attach_function 'set_control_g51', [ExcelValue.by_value], :void
    attach_function 'set_control_g52', [ExcelValue.by_value], :void
    attach_function 'set_control_g53', [ExcelValue.by_value], :void
    attach_function 'set_control_g54', [ExcelValue.by_value], :void
    attach_function 'set_control_g55', [ExcelValue.by_value], :void
    attach_function 'set_control_g56', [ExcelValue.by_value], :void
    attach_function 'set_control_g57', [ExcelValue.by_value], :void
    attach_function 'set_control_g58', [ExcelValue.by_value], :void
    attach_function 'set_control_g59', [ExcelValue.by_value], :void
    attach_function 'set_control_g60', [ExcelValue.by_value], :void
    attach_function 'set_control_g61', [ExcelValue.by_value], :void
    attach_function 'set_control_g62', [ExcelValue.by_value], :void
    attach_function 'set_control_g63', [ExcelValue.by_value], :void
    attach_function 'set_control_g64', [ExcelValue.by_value], :void
    attach_function 'set_control_g65', [ExcelValue.by_value], :void
    attach_function 'set_control_g66', [ExcelValue.by_value], :void
    attach_function 'set_control_g67', [ExcelValue.by_value], :void
    attach_function 'set_control_e17', [ExcelValue.by_value], :void
    attach_function 'set_control_e18', [ExcelValue.by_value], :void
    attach_function 'set_control_e19', [ExcelValue.by_value], :void
    attach_function 'set_control_e20', [ExcelValue.by_value], :void
    attach_function 'set_control_e21', [ExcelValue.by_value], :void
    attach_function 'set_control_e22', [ExcelValue.by_value], :void
    attach_function 'set_control_e23', [ExcelValue.by_value], :void
    attach_function 'set_control_e24', [ExcelValue.by_value], :void
    attach_function 'set_control_e25', [ExcelValue.by_value], :void
    attach_function 'set_control_e26', [ExcelValue.by_value], :void
    attach_function 'set_control_e27', [ExcelValue.by_value], :void
    attach_function 'set_control_e28', [ExcelValue.by_value], :void
    attach_function 'set_control_e29', [ExcelValue.by_value], :void
    attach_function 'set_control_e30', [ExcelValue.by_value], :void
    attach_function 'set_control_e31', [ExcelValue.by_value], :void
    attach_function 'set_control_e32', [ExcelValue.by_value], :void
    attach_function 'set_control_e33', [ExcelValue.by_value], :void
    attach_function 'set_control_e34', [ExcelValue.by_value], :void
    attach_function 'set_control_e35', [ExcelValue.by_value], :void
    attach_function 'set_control_e36', [ExcelValue.by_value], :void
    attach_function 'set_control_e37', [ExcelValue.by_value], :void
    attach_function 'set_control_e38', [ExcelValue.by_value], :void
    attach_function 'set_control_e39', [ExcelValue.by_value], :void
    attach_function 'set_control_e40', [ExcelValue.by_value], :void
    attach_function 'set_control_e41', [ExcelValue.by_value], :void
    attach_function 'set_control_e42', [ExcelValue.by_value], :void
    attach_function 'set_control_e43', [ExcelValue.by_value], :void
    attach_function 'set_control_e44', [ExcelValue.by_value], :void
    attach_function 'set_control_e45', [ExcelValue.by_value], :void
    attach_function 'set_control_e46', [ExcelValue.by_value], :void
    attach_function 'set_control_e47', [ExcelValue.by_value], :void
    attach_function 'set_control_e48', [ExcelValue.by_value], :void
    attach_function 'set_control_e49', [ExcelValue.by_value], :void
    attach_function 'set_control_e50', [ExcelValue.by_value], :void
    attach_function 'set_control_e51', [ExcelValue.by_value], :void
    attach_function 'set_control_e52', [ExcelValue.by_value], :void
    attach_function 'set_control_e53', [ExcelValue.by_value], :void
    attach_function 'set_control_e54', [ExcelValue.by_value], :void
    attach_function 'set_control_e55', [ExcelValue.by_value], :void
    attach_function 'set_control_e56', [ExcelValue.by_value], :void
    attach_function 'set_control_e57', [ExcelValue.by_value], :void
    attach_function 'set_control_e58', [ExcelValue.by_value], :void
    attach_function 'set_control_e59', [ExcelValue.by_value], :void
    attach_function 'set_control_e60', [ExcelValue.by_value], :void
    attach_function 'set_control_e61', [ExcelValue.by_value], :void
    attach_function 'set_control_e62', [ExcelValue.by_value], :void
    attach_function 'set_control_e63', [ExcelValue.by_value], :void
    attach_function 'set_control_e64', [ExcelValue.by_value], :void
    attach_function 'set_control_e65', [ExcelValue.by_value], :void
    attach_function 'set_control_e66', [ExcelValue.by_value], :void
    attach_function 'set_control_e67', [ExcelValue.by_value], :void
    attach_function 'control_i16', [], ExcelValue.by_value
    attach_function 'control_i17', [], ExcelValue.by_value
    attach_function 'control_i18', [], ExcelValue.by_value
    attach_function 'control_i19', [], ExcelValue.by_value
    attach_function 'control_i20', [], ExcelValue.by_value
    attach_function 'control_i21', [], ExcelValue.by_value
    attach_function 'control_i22', [], ExcelValue.by_value
    attach_function 'control_i23', [], ExcelValue.by_value
    attach_function 'control_i24', [], ExcelValue.by_value
    attach_function 'control_i25', [], ExcelValue.by_value
    attach_function 'control_i26', [], ExcelValue.by_value
    attach_function 'control_i27', [], ExcelValue.by_value
    attach_function 'control_i28', [], ExcelValue.by_value
    attach_function 'control_i29', [], ExcelValue.by_value
    attach_function 'control_i30', [], ExcelValue.by_value
    attach_function 'control_i31', [], ExcelValue.by_value
    attach_function 'control_i32', [], ExcelValue.by_value
    attach_function 'control_i33', [], ExcelValue.by_value
    attach_function 'control_i34', [], ExcelValue.by_value
    attach_function 'control_i35', [], ExcelValue.by_value
    attach_function 'control_i36', [], ExcelValue.by_value
    attach_function 'control_i37', [], ExcelValue.by_value
    attach_function 'control_i38', [], ExcelValue.by_value
    attach_function 'control_i39', [], ExcelValue.by_value
    attach_function 'control_i40', [], ExcelValue.by_value
    attach_function 'control_i41', [], ExcelValue.by_value
    attach_function 'control_i42', [], ExcelValue.by_value
    attach_function 'control_i43', [], ExcelValue.by_value
    attach_function 'control_i44', [], ExcelValue.by_value
    attach_function 'control_i45', [], ExcelValue.by_value
    attach_function 'control_i46', [], ExcelValue.by_value
    attach_function 'control_i47', [], ExcelValue.by_value
    attach_function 'control_i48', [], ExcelValue.by_value
    attach_function 'control_i49', [], ExcelValue.by_value
    attach_function 'control_i50', [], ExcelValue.by_value
    attach_function 'control_i51', [], ExcelValue.by_value
    attach_function 'control_i52', [], ExcelValue.by_value
    attach_function 'control_i53', [], ExcelValue.by_value
    attach_function 'control_i54', [], ExcelValue.by_value
    attach_function 'control_i55', [], ExcelValue.by_value
    attach_function 'control_i56', [], ExcelValue.by_value
    attach_function 'control_i57', [], ExcelValue.by_value
    attach_function 'control_i58', [], ExcelValue.by_value
    attach_function 'control_i59', [], ExcelValue.by_value
    attach_function 'control_i60', [], ExcelValue.by_value
    attach_function 'control_i61', [], ExcelValue.by_value
    attach_function 'control_i62', [], ExcelValue.by_value
    attach_function 'control_i63', [], ExcelValue.by_value
    attach_function 'control_i64', [], ExcelValue.by_value
    attach_function 'control_i65', [], ExcelValue.by_value
    attach_function 'control_i66', [], ExcelValue.by_value
    attach_function 'control_i67', [], ExcelValue.by_value
    attach_function 'control_i68', [], ExcelValue.by_value
    attach_function 'control_i69', [], ExcelValue.by_value
    attach_function 'control_d17', [], ExcelValue.by_value
    attach_function 'control_d18', [], ExcelValue.by_value
    attach_function 'control_d19', [], ExcelValue.by_value
    attach_function 'control_d20', [], ExcelValue.by_value
    attach_function 'control_d21', [], ExcelValue.by_value
    attach_function 'control_d22', [], ExcelValue.by_value
    attach_function 'control_d23', [], ExcelValue.by_value
    attach_function 'control_d24', [], ExcelValue.by_value
    attach_function 'control_d25', [], ExcelValue.by_value
    attach_function 'control_d26', [], ExcelValue.by_value
    attach_function 'control_d27', [], ExcelValue.by_value
    attach_function 'control_d28', [], ExcelValue.by_value
    attach_function 'control_d29', [], ExcelValue.by_value
    attach_function 'control_d30', [], ExcelValue.by_value
    attach_function 'control_d31', [], ExcelValue.by_value
    attach_function 'control_d32', [], ExcelValue.by_value
    attach_function 'control_d33', [], ExcelValue.by_value
    attach_function 'control_d34', [], ExcelValue.by_value
    attach_function 'control_d35', [], ExcelValue.by_value
    attach_function 'control_d36', [], ExcelValue.by_value
    attach_function 'control_d37', [], ExcelValue.by_value
    attach_function 'control_d38', [], ExcelValue.by_value
    attach_function 'control_d39', [], ExcelValue.by_value
    attach_function 'control_d40', [], ExcelValue.by_value
    attach_function 'control_d41', [], ExcelValue.by_value
    attach_function 'control_d42', [], ExcelValue.by_value
    attach_function 'control_d43', [], ExcelValue.by_value
    attach_function 'control_d44', [], ExcelValue.by_value
    attach_function 'control_d45', [], ExcelValue.by_value
    attach_function 'control_d46', [], ExcelValue.by_value
    attach_function 'control_d47', [], ExcelValue.by_value
    attach_function 'control_d48', [], ExcelValue.by_value
    attach_function 'control_d49', [], ExcelValue.by_value
    attach_function 'control_d50', [], ExcelValue.by_value
    attach_function 'control_d51', [], ExcelValue.by_value
    attach_function 'control_d52', [], ExcelValue.by_value
    attach_function 'control_d53', [], ExcelValue.by_value
    attach_function 'control_d54', [], ExcelValue.by_value
    attach_function 'control_d55', [], ExcelValue.by_value
    attach_function 'control_d56', [], ExcelValue.by_value
    attach_function 'control_d57', [], ExcelValue.by_value
    attach_function 'control_d58', [], ExcelValue.by_value
    attach_function 'control_d59', [], ExcelValue.by_value
    attach_function 'control_d60', [], ExcelValue.by_value
    attach_function 'control_d61', [], ExcelValue.by_value
    attach_function 'control_d62', [], ExcelValue.by_value
    attach_function 'control_d63', [], ExcelValue.by_value
    attach_function 'control_d64', [], ExcelValue.by_value
    attach_function 'control_d65', [], ExcelValue.by_value
    attach_function 'control_d66', [], ExcelValue.by_value
    attach_function 'control_d67', [], ExcelValue.by_value
    attach_function 'control_g17', [], ExcelValue.by_value
    attach_function 'control_g18', [], ExcelValue.by_value
    attach_function 'control_g19', [], ExcelValue.by_value
    attach_function 'control_g20', [], ExcelValue.by_value
    attach_function 'control_g21', [], ExcelValue.by_value
    attach_function 'control_g22', [], ExcelValue.by_value
    attach_function 'control_g23', [], ExcelValue.by_value
    attach_function 'control_g24', [], ExcelValue.by_value
    attach_function 'control_g25', [], ExcelValue.by_value
    attach_function 'control_g26', [], ExcelValue.by_value
    attach_function 'control_g27', [], ExcelValue.by_value
    attach_function 'control_g28', [], ExcelValue.by_value
    attach_function 'control_g29', [], ExcelValue.by_value
    attach_function 'control_g30', [], ExcelValue.by_value
    attach_function 'control_g31', [], ExcelValue.by_value
    attach_function 'control_g32', [], ExcelValue.by_value
    attach_function 'control_g33', [], ExcelValue.by_value
    attach_function 'control_g34', [], ExcelValue.by_value
    attach_function 'control_g35', [], ExcelValue.by_value
    attach_function 'control_g36', [], ExcelValue.by_value
    attach_function 'control_g37', [], ExcelValue.by_value
    attach_function 'control_g38', [], ExcelValue.by_value
    attach_function 'control_g39', [], ExcelValue.by_value
    attach_function 'control_g40', [], ExcelValue.by_value
    attach_function 'control_g41', [], ExcelValue.by_value
    attach_function 'control_g42', [], ExcelValue.by_value
    attach_function 'control_g43', [], ExcelValue.by_value
    attach_function 'control_g44', [], ExcelValue.by_value
    attach_function 'control_g45', [], ExcelValue.by_value
    attach_function 'control_g46', [], ExcelValue.by_value
    attach_function 'control_g47', [], ExcelValue.by_value
    attach_function 'control_g48', [], ExcelValue.by_value
    attach_function 'control_g49', [], ExcelValue.by_value
    attach_function 'control_g50', [], ExcelValue.by_value
    attach_function 'control_g51', [], ExcelValue.by_value
    attach_function 'control_g52', [], ExcelValue.by_value
    attach_function 'control_g53', [], ExcelValue.by_value
    attach_function 'control_g54', [], ExcelValue.by_value
    attach_function 'control_g55', [], ExcelValue.by_value
    attach_function 'control_g56', [], ExcelValue.by_value
    attach_function 'control_g57', [], ExcelValue.by_value
    attach_function 'control_g58', [], ExcelValue.by_value
    attach_function 'control_g59', [], ExcelValue.by_value
    attach_function 'control_g60', [], ExcelValue.by_value
    attach_function 'control_g61', [], ExcelValue.by_value
    attach_function 'control_g62', [], ExcelValue.by_value
    attach_function 'control_g63', [], ExcelValue.by_value
    attach_function 'control_g64', [], ExcelValue.by_value
    attach_function 'control_g65', [], ExcelValue.by_value
    attach_function 'control_g66', [], ExcelValue.by_value
    attach_function 'control_g67', [], ExcelValue.by_value
    attach_function 'control_e17', [], ExcelValue.by_value
    attach_function 'control_e18', [], ExcelValue.by_value
    attach_function 'control_e19', [], ExcelValue.by_value
    attach_function 'control_e20', [], ExcelValue.by_value
    attach_function 'control_e21', [], ExcelValue.by_value
    attach_function 'control_e22', [], ExcelValue.by_value
    attach_function 'control_e23', [], ExcelValue.by_value
    attach_function 'control_e24', [], ExcelValue.by_value
    attach_function 'control_e25', [], ExcelValue.by_value
    attach_function 'control_e26', [], ExcelValue.by_value
    attach_function 'control_e27', [], ExcelValue.by_value
    attach_function 'control_e28', [], ExcelValue.by_value
    attach_function 'control_e29', [], ExcelValue.by_value
    attach_function 'control_e30', [], ExcelValue.by_value
    attach_function 'control_e31', [], ExcelValue.by_value
    attach_function 'control_e32', [], ExcelValue.by_value
    attach_function 'control_e33', [], ExcelValue.by_value
    attach_function 'control_e34', [], ExcelValue.by_value
    attach_function 'control_e35', [], ExcelValue.by_value
    attach_function 'control_e36', [], ExcelValue.by_value
    attach_function 'control_e37', [], ExcelValue.by_value
    attach_function 'control_e38', [], ExcelValue.by_value
    attach_function 'control_e39', [], ExcelValue.by_value
    attach_function 'control_e40', [], ExcelValue.by_value
    attach_function 'control_e41', [], ExcelValue.by_value
    attach_function 'control_e42', [], ExcelValue.by_value
    attach_function 'control_e43', [], ExcelValue.by_value
    attach_function 'control_e44', [], ExcelValue.by_value
    attach_function 'control_e45', [], ExcelValue.by_value
    attach_function 'control_e46', [], ExcelValue.by_value
    attach_function 'control_e47', [], ExcelValue.by_value
    attach_function 'control_e48', [], ExcelValue.by_value
    attach_function 'control_e49', [], ExcelValue.by_value
    attach_function 'control_e50', [], ExcelValue.by_value
    attach_function 'control_e51', [], ExcelValue.by_value
    attach_function 'control_e52', [], ExcelValue.by_value
    attach_function 'control_e53', [], ExcelValue.by_value
    attach_function 'control_e54', [], ExcelValue.by_value
    attach_function 'control_e55', [], ExcelValue.by_value
    attach_function 'control_e56', [], ExcelValue.by_value
    attach_function 'control_e57', [], ExcelValue.by_value
    attach_function 'control_e58', [], ExcelValue.by_value
    attach_function 'control_e59', [], ExcelValue.by_value
    attach_function 'control_e60', [], ExcelValue.by_value
    attach_function 'control_e61', [], ExcelValue.by_value
    attach_function 'control_e62', [], ExcelValue.by_value
    attach_function 'control_e63', [], ExcelValue.by_value
    attach_function 'control_e64', [], ExcelValue.by_value
    attach_function 'control_e65', [], ExcelValue.by_value
    attach_function 'control_e66', [], ExcelValue.by_value
    attach_function 'control_e67', [], ExcelValue.by_value
    attach_function 'control_ef17', [], ExcelValue.by_value
    attach_function 'control_eg17', [], ExcelValue.by_value
    attach_function 'control_eh17', [], ExcelValue.by_value
    attach_function 'control_ei17', [], ExcelValue.by_value
    attach_function 'control_ef18', [], ExcelValue.by_value
    attach_function 'control_eg18', [], ExcelValue.by_value
    attach_function 'control_eh18', [], ExcelValue.by_value
    attach_function 'control_ei18', [], ExcelValue.by_value
    attach_function 'control_ef19', [], ExcelValue.by_value
    attach_function 'control_eg19', [], ExcelValue.by_value
    attach_function 'control_eh19', [], ExcelValue.by_value
    attach_function 'control_ei19', [], ExcelValue.by_value
    attach_function 'control_ef20', [], ExcelValue.by_value
    attach_function 'control_eg20', [], ExcelValue.by_value
    attach_function 'control_eh20', [], ExcelValue.by_value
    attach_function 'control_ei20', [], ExcelValue.by_value
    attach_function 'control_ef21', [], ExcelValue.by_value
    attach_function 'control_eg21', [], ExcelValue.by_value
    attach_function 'control_eh21', [], ExcelValue.by_value
    attach_function 'control_ei21', [], ExcelValue.by_value
    attach_function 'control_ef22', [], ExcelValue.by_value
    attach_function 'control_eg22', [], ExcelValue.by_value
    attach_function 'control_eh22', [], ExcelValue.by_value
    attach_function 'control_ei22', [], ExcelValue.by_value
    attach_function 'control_ef23', [], ExcelValue.by_value
    attach_function 'control_eg23', [], ExcelValue.by_value
    attach_function 'control_eh23', [], ExcelValue.by_value
    attach_function 'control_ei23', [], ExcelValue.by_value
    attach_function 'control_ef24', [], ExcelValue.by_value
    attach_function 'control_eg24', [], ExcelValue.by_value
    attach_function 'control_eh24', [], ExcelValue.by_value
    attach_function 'control_ei24', [], ExcelValue.by_value
    attach_function 'control_ef25', [], ExcelValue.by_value
    attach_function 'control_eg25', [], ExcelValue.by_value
    attach_function 'control_eh25', [], ExcelValue.by_value
    attach_function 'control_ei25', [], ExcelValue.by_value
    attach_function 'control_ef26', [], ExcelValue.by_value
    attach_function 'control_eg26', [], ExcelValue.by_value
    attach_function 'control_eh26', [], ExcelValue.by_value
    attach_function 'control_ei26', [], ExcelValue.by_value
    attach_function 'control_ef27', [], ExcelValue.by_value
    attach_function 'control_eg27', [], ExcelValue.by_value
    attach_function 'control_eh27', [], ExcelValue.by_value
    attach_function 'control_ei27', [], ExcelValue.by_value
    attach_function 'control_ef28', [], ExcelValue.by_value
    attach_function 'control_eg28', [], ExcelValue.by_value
    attach_function 'control_eh28', [], ExcelValue.by_value
    attach_function 'control_ei28', [], ExcelValue.by_value
    attach_function 'control_ef29', [], ExcelValue.by_value
    attach_function 'control_eg29', [], ExcelValue.by_value
    attach_function 'control_eh29', [], ExcelValue.by_value
    attach_function 'control_ei29', [], ExcelValue.by_value
    attach_function 'control_ef30', [], ExcelValue.by_value
    attach_function 'control_eg30', [], ExcelValue.by_value
    attach_function 'control_eh30', [], ExcelValue.by_value
    attach_function 'control_ei30', [], ExcelValue.by_value
    attach_function 'control_ef31', [], ExcelValue.by_value
    attach_function 'control_eg31', [], ExcelValue.by_value
    attach_function 'control_eh31', [], ExcelValue.by_value
    attach_function 'control_ei31', [], ExcelValue.by_value
    attach_function 'control_ef32', [], ExcelValue.by_value
    attach_function 'control_eg32', [], ExcelValue.by_value
    attach_function 'control_eh32', [], ExcelValue.by_value
    attach_function 'control_ei32', [], ExcelValue.by_value
    attach_function 'control_ef33', [], ExcelValue.by_value
    attach_function 'control_eg33', [], ExcelValue.by_value
    attach_function 'control_eh33', [], ExcelValue.by_value
    attach_function 'control_ei33', [], ExcelValue.by_value
    attach_function 'control_ef34', [], ExcelValue.by_value
    attach_function 'control_eg34', [], ExcelValue.by_value
    attach_function 'control_eh34', [], ExcelValue.by_value
    attach_function 'control_ei34', [], ExcelValue.by_value
    attach_function 'control_ef35', [], ExcelValue.by_value
    attach_function 'control_eg35', [], ExcelValue.by_value
    attach_function 'control_eh35', [], ExcelValue.by_value
    attach_function 'control_ei35', [], ExcelValue.by_value
    attach_function 'control_ef36', [], ExcelValue.by_value
    attach_function 'control_eg36', [], ExcelValue.by_value
    attach_function 'control_eh36', [], ExcelValue.by_value
    attach_function 'control_ei36', [], ExcelValue.by_value
    attach_function 'control_ef37', [], ExcelValue.by_value
    attach_function 'control_eg37', [], ExcelValue.by_value
    attach_function 'control_eh37', [], ExcelValue.by_value
    attach_function 'control_ei37', [], ExcelValue.by_value
    attach_function 'control_ef38', [], ExcelValue.by_value
    attach_function 'control_eg38', [], ExcelValue.by_value
    attach_function 'control_eh38', [], ExcelValue.by_value
    attach_function 'control_ei38', [], ExcelValue.by_value
    attach_function 'control_ef39', [], ExcelValue.by_value
    attach_function 'control_eg39', [], ExcelValue.by_value
    attach_function 'control_eh39', [], ExcelValue.by_value
    attach_function 'control_ei39', [], ExcelValue.by_value
    attach_function 'control_ef40', [], ExcelValue.by_value
    attach_function 'control_eg40', [], ExcelValue.by_value
    attach_function 'control_eh40', [], ExcelValue.by_value
    attach_function 'control_ei40', [], ExcelValue.by_value
    attach_function 'control_ef41', [], ExcelValue.by_value
    attach_function 'control_eg41', [], ExcelValue.by_value
    attach_function 'control_eh41', [], ExcelValue.by_value
    attach_function 'control_ei41', [], ExcelValue.by_value
    attach_function 'control_ef42', [], ExcelValue.by_value
    attach_function 'control_eg42', [], ExcelValue.by_value
    attach_function 'control_eh42', [], ExcelValue.by_value
    attach_function 'control_ei42', [], ExcelValue.by_value
    attach_function 'control_ef43', [], ExcelValue.by_value
    attach_function 'control_eg43', [], ExcelValue.by_value
    attach_function 'control_eh43', [], ExcelValue.by_value
    attach_function 'control_ei43', [], ExcelValue.by_value
    attach_function 'control_ef44', [], ExcelValue.by_value
    attach_function 'control_eg44', [], ExcelValue.by_value
    attach_function 'control_eh44', [], ExcelValue.by_value
    attach_function 'control_ei44', [], ExcelValue.by_value
    attach_function 'control_ef45', [], ExcelValue.by_value
    attach_function 'control_eg45', [], ExcelValue.by_value
    attach_function 'control_eh45', [], ExcelValue.by_value
    attach_function 'control_ei45', [], ExcelValue.by_value
    attach_function 'control_ef46', [], ExcelValue.by_value
    attach_function 'control_eg46', [], ExcelValue.by_value
    attach_function 'control_eh46', [], ExcelValue.by_value
    attach_function 'control_ei46', [], ExcelValue.by_value
    attach_function 'control_ef47', [], ExcelValue.by_value
    attach_function 'control_eg47', [], ExcelValue.by_value
    attach_function 'control_eh47', [], ExcelValue.by_value
    attach_function 'control_ei47', [], ExcelValue.by_value
    attach_function 'control_ef48', [], ExcelValue.by_value
    attach_function 'control_eg48', [], ExcelValue.by_value
    attach_function 'control_eh48', [], ExcelValue.by_value
    attach_function 'control_ei48', [], ExcelValue.by_value
    attach_function 'control_ef49', [], ExcelValue.by_value
    attach_function 'control_eg49', [], ExcelValue.by_value
    attach_function 'control_eh49', [], ExcelValue.by_value
    attach_function 'control_ei49', [], ExcelValue.by_value
    attach_function 'control_ef50', [], ExcelValue.by_value
    attach_function 'control_eg50', [], ExcelValue.by_value
    attach_function 'control_eh50', [], ExcelValue.by_value
    attach_function 'control_ei50', [], ExcelValue.by_value
    attach_function 'control_ef51', [], ExcelValue.by_value
    attach_function 'control_eg51', [], ExcelValue.by_value
    attach_function 'control_eh51', [], ExcelValue.by_value
    attach_function 'control_ei51', [], ExcelValue.by_value
    attach_function 'control_ef52', [], ExcelValue.by_value
    attach_function 'control_eg52', [], ExcelValue.by_value
    attach_function 'control_eh52', [], ExcelValue.by_value
    attach_function 'control_ei52', [], ExcelValue.by_value
    attach_function 'control_ef53', [], ExcelValue.by_value
    attach_function 'control_eg53', [], ExcelValue.by_value
    attach_function 'control_eh53', [], ExcelValue.by_value
    attach_function 'control_ei53', [], ExcelValue.by_value
    attach_function 'control_ef54', [], ExcelValue.by_value
    attach_function 'control_eg54', [], ExcelValue.by_value
    attach_function 'control_eh54', [], ExcelValue.by_value
    attach_function 'control_ei54', [], ExcelValue.by_value
    attach_function 'control_ef55', [], ExcelValue.by_value
    attach_function 'control_eg55', [], ExcelValue.by_value
    attach_function 'control_eh55', [], ExcelValue.by_value
    attach_function 'control_ei55', [], ExcelValue.by_value
    attach_function 'control_ef56', [], ExcelValue.by_value
    attach_function 'control_eg56', [], ExcelValue.by_value
    attach_function 'control_eh56', [], ExcelValue.by_value
    attach_function 'control_ei56', [], ExcelValue.by_value
    attach_function 'control_ef57', [], ExcelValue.by_value
    attach_function 'control_eg57', [], ExcelValue.by_value
    attach_function 'control_eh57', [], ExcelValue.by_value
    attach_function 'control_ei57', [], ExcelValue.by_value
    attach_function 'control_ef58', [], ExcelValue.by_value
    attach_function 'control_eg58', [], ExcelValue.by_value
    attach_function 'control_eh58', [], ExcelValue.by_value
    attach_function 'control_ei58', [], ExcelValue.by_value
    attach_function 'control_ef59', [], ExcelValue.by_value
    attach_function 'control_eg59', [], ExcelValue.by_value
    attach_function 'control_eh59', [], ExcelValue.by_value
    attach_function 'control_ei59', [], ExcelValue.by_value
    attach_function 'control_ef60', [], ExcelValue.by_value
    attach_function 'control_eg60', [], ExcelValue.by_value
    attach_function 'control_eh60', [], ExcelValue.by_value
    attach_function 'control_ei60', [], ExcelValue.by_value
    attach_function 'control_ef61', [], ExcelValue.by_value
    attach_function 'control_eg61', [], ExcelValue.by_value
    attach_function 'control_eh61', [], ExcelValue.by_value
    attach_function 'control_ei61', [], ExcelValue.by_value
    attach_function 'control_ef62', [], ExcelValue.by_value
    attach_function 'control_eg62', [], ExcelValue.by_value
    attach_function 'control_eh62', [], ExcelValue.by_value
    attach_function 'control_ei62', [], ExcelValue.by_value
    attach_function 'control_ef63', [], ExcelValue.by_value
    attach_function 'control_eg63', [], ExcelValue.by_value
    attach_function 'control_eh63', [], ExcelValue.by_value
    attach_function 'control_ei63', [], ExcelValue.by_value
    attach_function 'control_ef64', [], ExcelValue.by_value
    attach_function 'control_eg64', [], ExcelValue.by_value
    attach_function 'control_eh64', [], ExcelValue.by_value
    attach_function 'control_ei64', [], ExcelValue.by_value
    attach_function 'control_ef65', [], ExcelValue.by_value
    attach_function 'control_eg65', [], ExcelValue.by_value
    attach_function 'control_eh65', [], ExcelValue.by_value
    attach_function 'control_ei65', [], ExcelValue.by_value
    attach_function 'control_ef66', [], ExcelValue.by_value
    attach_function 'control_eg66', [], ExcelValue.by_value
    attach_function 'control_eh66', [], ExcelValue.by_value
    attach_function 'control_ei66', [], ExcelValue.by_value
    attach_function 'control_ef67', [], ExcelValue.by_value
    attach_function 'control_eg67', [], ExcelValue.by_value
    attach_function 'control_eh67', [], ExcelValue.by_value
    attach_function 'control_ei67', [], ExcelValue.by_value
    attach_function 'control_c17', [], ExcelValue.by_value
    attach_function 'control_c18', [], ExcelValue.by_value
    attach_function 'control_c19', [], ExcelValue.by_value
    attach_function 'control_c20', [], ExcelValue.by_value
    attach_function 'control_c21', [], ExcelValue.by_value
    attach_function 'control_c22', [], ExcelValue.by_value
    attach_function 'control_c23', [], ExcelValue.by_value
    attach_function 'control_c24', [], ExcelValue.by_value
    attach_function 'control_c25', [], ExcelValue.by_value
    attach_function 'control_c26', [], ExcelValue.by_value
    attach_function 'control_c27', [], ExcelValue.by_value
    attach_function 'control_c28', [], ExcelValue.by_value
    attach_function 'control_c29', [], ExcelValue.by_value
    attach_function 'control_c30', [], ExcelValue.by_value
    attach_function 'control_c31', [], ExcelValue.by_value
    attach_function 'control_c32', [], ExcelValue.by_value
    attach_function 'control_c33', [], ExcelValue.by_value
    attach_function 'control_c34', [], ExcelValue.by_value
    attach_function 'control_c35', [], ExcelValue.by_value
    attach_function 'control_c36', [], ExcelValue.by_value
    attach_function 'control_c37', [], ExcelValue.by_value
    attach_function 'control_c38', [], ExcelValue.by_value
    attach_function 'control_c39', [], ExcelValue.by_value
    attach_function 'control_c40', [], ExcelValue.by_value
    attach_function 'control_c41', [], ExcelValue.by_value
    attach_function 'control_c42', [], ExcelValue.by_value
    attach_function 'control_c43', [], ExcelValue.by_value
    attach_function 'control_c44', [], ExcelValue.by_value
    attach_function 'control_c45', [], ExcelValue.by_value
    attach_function 'control_c46', [], ExcelValue.by_value
    attach_function 'control_c47', [], ExcelValue.by_value
    attach_function 'control_c48', [], ExcelValue.by_value
    attach_function 'control_c49', [], ExcelValue.by_value
    attach_function 'control_c50', [], ExcelValue.by_value
    attach_function 'control_c51', [], ExcelValue.by_value
    attach_function 'control_c52', [], ExcelValue.by_value
    attach_function 'control_c53', [], ExcelValue.by_value
    attach_function 'control_c54', [], ExcelValue.by_value
    attach_function 'control_c55', [], ExcelValue.by_value
    attach_function 'control_c56', [], ExcelValue.by_value
    attach_function 'control_c57', [], ExcelValue.by_value
    attach_function 'control_c58', [], ExcelValue.by_value
    attach_function 'control_c59', [], ExcelValue.by_value
    attach_function 'control_c60', [], ExcelValue.by_value
    attach_function 'control_c61', [], ExcelValue.by_value
    attach_function 'control_c62', [], ExcelValue.by_value
    attach_function 'control_c63', [], ExcelValue.by_value
    attach_function 'control_c64', [], ExcelValue.by_value
    attach_function 'control_c65', [], ExcelValue.by_value
    attach_function 'control_c66', [], ExcelValue.by_value
    attach_function 'control_c67', [], ExcelValue.by_value
    attach_function 'control_h17', [], ExcelValue.by_value
    attach_function 'control_h18', [], ExcelValue.by_value
    attach_function 'control_h19', [], ExcelValue.by_value
    attach_function 'control_h20', [], ExcelValue.by_value
    attach_function 'control_h21', [], ExcelValue.by_value
    attach_function 'control_h22', [], ExcelValue.by_value
    attach_function 'control_h23', [], ExcelValue.by_value
    attach_function 'control_h24', [], ExcelValue.by_value
    attach_function 'control_h25', [], ExcelValue.by_value
    attach_function 'control_h26', [], ExcelValue.by_value
    attach_function 'control_h27', [], ExcelValue.by_value
    attach_function 'control_h28', [], ExcelValue.by_value
    attach_function 'control_h29', [], ExcelValue.by_value
    attach_function 'control_h30', [], ExcelValue.by_value
    attach_function 'control_h31', [], ExcelValue.by_value
    attach_function 'control_h32', [], ExcelValue.by_value
    attach_function 'control_h33', [], ExcelValue.by_value
    attach_function 'control_h34', [], ExcelValue.by_value
    attach_function 'control_h35', [], ExcelValue.by_value
    attach_function 'control_h36', [], ExcelValue.by_value
    attach_function 'control_h37', [], ExcelValue.by_value
    attach_function 'control_h38', [], ExcelValue.by_value
    attach_function 'control_h39', [], ExcelValue.by_value
    attach_function 'control_h40', [], ExcelValue.by_value
    attach_function 'control_h41', [], ExcelValue.by_value
    attach_function 'control_h42', [], ExcelValue.by_value
    attach_function 'control_h43', [], ExcelValue.by_value
    attach_function 'control_h44', [], ExcelValue.by_value
    attach_function 'control_h45', [], ExcelValue.by_value
    attach_function 'control_h46', [], ExcelValue.by_value
    attach_function 'control_h47', [], ExcelValue.by_value
    attach_function 'control_h48', [], ExcelValue.by_value
    attach_function 'control_h49', [], ExcelValue.by_value
    attach_function 'control_h50', [], ExcelValue.by_value
    attach_function 'control_h51', [], ExcelValue.by_value
    attach_function 'control_h52', [], ExcelValue.by_value
    attach_function 'control_h53', [], ExcelValue.by_value
    attach_function 'control_h54', [], ExcelValue.by_value
    attach_function 'control_h55', [], ExcelValue.by_value
    attach_function 'control_h56', [], ExcelValue.by_value
    attach_function 'control_h57', [], ExcelValue.by_value
    attach_function 'control_h58', [], ExcelValue.by_value
    attach_function 'control_h59', [], ExcelValue.by_value
    attach_function 'control_h60', [], ExcelValue.by_value
    attach_function 'control_h61', [], ExcelValue.by_value
    attach_function 'control_h62', [], ExcelValue.by_value
    attach_function 'control_h63', [], ExcelValue.by_value
    attach_function 'control_h64', [], ExcelValue.by_value
    attach_function 'control_h65', [], ExcelValue.by_value
    attach_function 'control_h66', [], ExcelValue.by_value
    attach_function 'control_h67', [], ExcelValue.by_value
    # end of Control
    # end of Webtool References
    # end of Sheet1
    # Start of named references
    attach_function 'input_example_pathways', [], ExcelValue.by_value
    attach_function 'input_lever_ambition', [], ExcelValue.by_value
    attach_function 'input_lever_end', [], ExcelValue.by_value
    attach_function 'input_lever_start', [], ExcelValue.by_value
    attach_function 'input_long_descriptions', [], ExcelValue.by_value
    attach_function 'input_names', [], ExcelValue.by_value
    attach_function 'input_types', [], ExcelValue.by_value
    attach_function 'output_electricity_capacity_type', [], ExcelValue.by_value
    attach_function 'output_electricity_generation_type', [], ExcelValue.by_value
    attach_function 'output_tra_car_type_share', [], ExcelValue.by_value
    attach_function 'output_tra_energy_consumption', [], ExcelValue.by_value
    attach_function 'input_example_pathways', [], ExcelValue.by_value
    attach_function 'input_lever_ambition', [], ExcelValue.by_value
    attach_function 'input_lever_end', [], ExcelValue.by_value
    attach_function 'input_lever_start', [], ExcelValue.by_value
    attach_function 'input_long_descriptions', [], ExcelValue.by_value
    attach_function 'input_names', [], ExcelValue.by_value
    attach_function 'input_types', [], ExcelValue.by_value
    attach_function 'output_electricity_capacity_type', [], ExcelValue.by_value
    attach_function 'output_electricity_generation_type', [], ExcelValue.by_value
    attach_function 'output_tra_car_type_share', [], ExcelValue.by_value
    attach_function 'output_tra_energy_consumption', [], ExcelValue.by_value
    attach_function 'set_input_lever_ambition', [ExcelValue.by_value], :void
    attach_function 'set_input_lever_end', [ExcelValue.by_value], :void
    attach_function 'set_input_lever_start', [ExcelValue.by_value], :void
    # End of named references
  end # C module
end # Model
